version: '3.9'

services:
  # db:
  #   image: postgres
  #   ports: 
  #     - "5432:5432"

  #   volumes:
  #     - ./db_data:/var/lib/postgresql/data
  #     - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   environment:
  #     - POSTGRES_DB=testdb
  #     - POSTGRES_USER=testuser
  #     - POSTGRES_PASSWORD=qwerty

  api:
    image: ghcr.io/sawcka/life-stat-backend:release
    command: bash -c "make run"

    environment:
      - DB_PASS=
      - DB_USER=
      - DB_HOST=
      - DB_NAME=
      - DB_PORT=
      - DB_ENV=DEV
      - SECRET_KEY=123

    deploy:
      mode: replicated
      replicas: 2

    restart: always

  web:
    image: ghcr.io/str1ve21/life-stat:release

    restart: always

    deploy:
      mode: replicated
      replicas: 2

  nginx:
    image: nginx:latest
    depends_on:
      - api
      - web
    restart: always
    ports:
      - "80:80"
    volumes:
      -  ./nginx.conf:/etc/nginx/nginx.conf
    
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - /root/.docker/config.json:/config.json
    command: --interval 10

    environment:
      - WATCHTOWER_ROLLING_RESTART=True